CREATE SEQUENCE IF NOT EXISTS O_CATEGORIES_SEQ
AS BIGINT
INCREMENT BY 1
MAXVALUE 99999999
START 1;
CREATE TABLE IF NOT EXISTS O_CATEGORIES(
    CATEGORY_ID BIGINT NOT NULL DEFAULT nextval('O_CATEGORIES_SEQ'),
    CATEGORY_NAME VARCHAR(40) NOT NULL,
    CATEGORY_TYPE VARCHAR(15) NOT NULL,
    CONSTRAINT O_CATEGORIES_PK PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT O_CATEGORIES_UQ UNIQUE (CATEGORY_NAME, CATEGORY_TYPE)
);
COMMENT ON COLUMN O_CATEGORIES.CATEGORY_ID IS 'Category identifier, ex: 1';
COMMENT ON COLUMN O_CATEGORIES.CATEGORY_NAME IS 'Category name, ex: Food';
COMMENT ON COLUMN O_CATEGORIES.CATEGORY_TYPE IS 'Category type, ex: Expense';