CREATE SEQUENCE IF NOT EXISTS O_CATEGORIES_SEQ
AS BIGINT
INCREMENT BY 1
MAXVALUE 99999999
START 1;
CREATE TABLE IF NOT EXISTS O_CATEGORIES(
    ID BIGINT NOT NULL DEFAULT nextval('O_CATEGORIES_SEQ'),
    NAME VARCHAR(40) NOT NULL,
    TYPE VARCHAR(15) NOT NULL,
    CONSTRAINT O_CATEGORIES_PK PRIMARY KEY (ID),
    CONSTRAINT O_CATEGORIES_UQ UNIQUE (NAME, TYPE)
);
COMMENT ON COLUMN O_CATEGORIES.ID IS 'Category identifier, ex: 1';
COMMENT ON COLUMN O_CATEGORIES.NAME IS 'Category name, ex: Food';
COMMENT ON COLUMN O_CATEGORIES.TYPE IS 'Category type, ex: Expense';