/************************************
* D_TRANSACTION_TYPE
************************************/
CREATE TABLE IF NOT EXISTS D_TRANSACTION_TYPE (
    TRANSACTION_TYPE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT D_TRANSACTION_TYPE_PK PRIMARY KEY (TRANSACTION_TYPE_ID)
);
COMMENT ON COLUMN D_TRANSACTION_TYPE.TRANSACTION_TYPE_ID IS 'Transaction type identifier, ex: EXPENSE';

/************************************
* O_CATEGORIES
************************************/
CREATE SEQUENCE IF NOT EXISTS O_CATEGORIES_SEQ
AS BIGINT
INCREMENT BY 1
MAXVALUE 99999999
START 1;
CREATE TABLE IF NOT EXISTS O_CATEGORIES(
    CATEGORY_ID BIGINT NOT NULL DEFAULT nextval('O_CATEGORIES_SEQ'),
    CATEGORY_NAME VARCHAR(40) NOT NULL,
    TRANSACTION_TYPE_ID VARCHAR(15) NOT NULL,
    CONSTRAINT O_CATEGORIES_PK PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT O_CATEGORIES_UQ UNIQUE (CATEGORY_NAME, TRANSACTION_TYPE_ID),
    CONSTRAINT O_CATEGORIES_D_TRANSACTION_TYPE FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES D_TRANSACTION_TYPE (TRANSACTION_TYPE_ID)
);
COMMENT ON COLUMN O_CATEGORIES.CATEGORY_ID IS 'Category identifier, ex: 1';
COMMENT ON COLUMN O_CATEGORIES.CATEGORY_NAME IS 'Category name, ex: Food';
COMMENT ON COLUMN O_CATEGORIES.TRANSACTION_TYPE_ID IS 'Transacton type identifier, ex: EXPENSE';

/************************************
* O_TRANSACTIONS
************************************/
CREATE SEQUENCE IF NOT EXISTS O_TRANSACTIONS_SEQ
AS BIGINT
INCREMENT BY 1
MAXVALUE 99999999
START 1;
CREATE TABLE IF NOT EXISTS O_TRANSACTIONS(
    TRANSACTION_ID BIGINT NOT NULL DEFAULT nextval('O_TRANSACTIONS_SEQ'),
    TRANSACTION_AMOUNT REAL NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    TRANSACTION_DESCRIPTION VARCHAR(254),
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT O_TRANSACTIONS_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT O_TRANSACTIONS_O_CATEGORIES_FK FOREIGN KEY (CATEGORY_ID) REFERENCES O_CATEGORIES (CATEGORY_ID),
    CONSTRAINT O_TRANSACTIONS_D_TRANSACTION_TYPE FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES D_TRANSACTION_TYPE (TRANSACTION_TYPE_ID)
);
COMMENT ON COLUMN O_TRANSACTIONS.TRANSACTION_ID IS 'Transaction unique identifier, ex: 1';
COMMENT ON COLUMN O_TRANSACTIONS.TRANSACTION_AMOUNT IS 'Transaction amount, ex: 2.55';
COMMENT ON COLUMN O_TRANSACTIONS.CATEGORY_ID IS 'Category identifier, ex: 1';
COMMENT ON COLUMN O_TRANSACTIONS.TRANSACTION_DESCRIPTION IS 'Transaction category, ex: Water';
COMMENT ON COLUMN O_TRANSACTIONS.TRANSACTION_DATE IS 'Transaction date, ex: 2024-01-01';
COMMENT ON COLUMN O_TRANSACTIONS.TRANSACTION_TYPE_ID IS 'Transacton type identifier, ex: EXPENSE';