spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      envers:
        audit_table_suffix: _AUD
        revision_field_name: REV
        revision_type_field_name: REV_TYPE
        revision_entity_class: com.mypersonalbook.economy.models.CustomRevisionMO
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}