spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/economy
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: sa
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: s15294970@gmail.com
    password: fcozjlvhfeofueqn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
SECRET_KEY: secretkey12312412e412eewe2341wdeqwe231234124123erqserrqeqweqdfqwedf
