spring:
  datasource:
    url: ${DATABASE_PREFIX}${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
SECRET_KEY: ${SECRET_KEY}
