spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/economy
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: sa
    password: root