spring:
  datasource:
    #url: jdbc:postgresql://localhost:5434/economy
    #username: sa
    #password: root
    url: jdbc:postgresql://monorail.proxy.rlwy.net:50836/railway
    username: postgres
    password: NJyGLgqMgpANMXFcuTcxsiwtTAtagwKl
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: postgres
    password: NJyGLgqMgpANMXFcuTcxsiwtTAtagwKl