CREATE SEQUENCE IF NOT EXISTS O_EXPENSES_SEQ
AS BIGINT
INCREMENT BY 1
MAXVALUE 99999999
START 1;
CREATE TABLE IF NOT EXISTS O_EXPENSES(
    EXPENSE_ID BIGINT NOT NULL DEFAULT nextval('O_EXPENSES_SEQ'),
    EXPENSE_AMOUNT REAL NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    EXPENSE_DESCRIPTION VARCHAR(254),
    EXPENSE_DATE DATE NOT NULL,
    CONSTRAINT O_EXPENSES_PK PRIMARY KEY (EXPENSE_ID),
    CONSTRAINT O_EXPENSES_O_CATEGORIES_FK FOREIGN KEY (CATEGORY_ID) REFERENCES O_CATEGORIES (CATEGORY_ID)
);
COMMENT ON COLUMN O_EXPENSES.EXPENSE_ID IS 'Expense unique identifier, ex: 1';
COMMENT ON COLUMN O_EXPENSES.EXPENSE_AMOUNT IS 'Expense amount, ex: 2.55';
COMMENT ON COLUMN O_EXPENSES.CATEGORY_ID IS 'Category identifier, ex: 1';
COMMENT ON COLUMN O_EXPENSES.EXPENSE_DESCRIPTION IS 'Expense category, ex: Water';
COMMENT ON COLUMN O_EXPENSES.EXPENSE_DATE IS 'Expense date, ex: 2024-01-01';